models.py
from sqlalchemy import Numeric, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship, mapped_column
from database import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = mapped_column(Integer, primary_key=True)
    username = mapped_column(String(100), unique=True, nullable=False)
    password = mapped_column(String(255), nullable=False)
    videos = relationship('Video', back_populates='user', lazy=True)

    def __init__(self, username, password):
        self.username = username
        self.password = password

class Video(db.Model):
    __tablename__ = 'video'
    id = mapped_column(Integer, primary_key=True)
    title = mapped_column(String(255), nullable=False)
    url = mapped_column(String(255), nullable=False)
    views = mapped_column(Integer, nullable=False)
    likes = mapped_column(Integer, nullable=False)
    dislikes = mapped_column(Integer, nullable=False)
    score = mapped_column(Numeric, nullable=False)
    word = mapped_column(Text, nullable=False)
    date = mapped_column(String(10), nullable=False)
    user_id = mapped_column(Integer, ForeignKey('user.id'), nullable=False)
    user = relationship('User', back_populates='videos')
    comments = relationship('Comment', back_populates='video', lazy=True)

class Comment(db.Model):
    __tablename__ = "comment"
    id = mapped_column(Integer, primary_key=True)
    text = mapped_column(Text, nullable=False)
    video_id = mapped_column(Integer, ForeignKey('video.id'), nullable=False)
    video = relationship('Video', back_populates='comments')

    def __init__(self, text, video_id):
        self.text = text
        self.video_id = video_id

app.py
from flask import Flask
from database import db
from pathlib import Path
from routes import auth_routes_bp, html_routes_bp
from flask_login import LoginManager
from models import User

app = Flask(__name__)
app.secret_key = "supersecretkey"
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///database.db"
app.instance_path = Path("./db").resolve()

db.init_app(app)
app.register_blueprint(auth_routes_bp, url_prefix="/")
app.register_blueprint(html_routes_bp, url_prefix="/views")
login_manager = LoginManager()
login_manager.login_view = "authorization.home"
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

if __name__ == "__main__":
    app.run(debug = True, host = "localhost", port=8008)

routes/__init__.py
from .auth import auth_routes_bp
from .html import html_routes_bp

routes/auth.py
from flask import url_for, render_template, request, Blueprint, redirect
from database import db
from models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

auth_routes_bp = Blueprint("authorization", __name__)

@auth_routes_bp.route("/")
def home():
    return render_template("/auth/login.html")

@auth_routes_bp.route("/auth/register")
def register():
    return render_template("/auth/signup.html")

@auth_routes_bp.route("/auth/login", methods=["POST"])
def login_post():
    username = request.form.get("username")
    password = request.form.get("password")
    statement = db.select(User).where(User.username == username)
    user = db.session.execute(statement).scalar()
    if not user or not check_password_hash(user.password, password):
        return redirect(url_for("authorization.home"))
    login_user(user)
    return redirect(url_for("html.home"))

@auth_routes_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("authorization.home"))

@auth_routes_bp.route("/auth/register", methods=["POST"])
def signup():
    username = request.form.get("username")
    password = request.form.get("password")
    if not username or not password:
        return redirect(url_for("authorization.register"))
    statement = db.select(User).where(User.username == username)
    user = db.session.execute(statement).scalar()
    if user:
        return redirect(url_for("authorization.register"))
    new_user = User(username = username, password = generate_password_hash(password, method="scrypt"))
    db.session.add(new_user)
    db.session.commit()
    return redirect(url_for("authorization.home"))

routes/html.py
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import login_required, current_user
from analyzer import *


html_routes_bp = Blueprint("html", __name__)

@html_routes_bp.route("/home")
@login_required
def home():
    return render_template("/html/home.html", user=current_user)

@html_routes_bp.route("/tutorial")
@login_required
def tutorial():
    return render_template("/html/tutorial.html")

@html_routes_bp.route("/dashboard", methods = ["POST"])

def read_url():
    from manage import new_video
    user = current_user           
    url = request.form["url"]
    pages = request.form["pages"]
    
    vid = urlToVid(url)

    if not vid:
        return redirect(url_for("html.home"))

    global title
    title = getTitle(vid)

    if not title:
        return redirect(url_for("html.home"))

    thumbnail = getThumbnail(vid)
    
    like_count, dislike_count, view_count = getStat(vid) # Fetch data from returndislike API
    word_comments, comments = getComment(vid, pages) # Process comments
    

    if word_comments or comments:
        most_occured_word = max(word_comments, key = word_comments.get) # Get most common word
        sentimentDict, avg_score = calculateScore(comments)
        new_video(current_user.id, getTitle(vid), url, view_count, like_count, dislike_count, avg_score, most_occured_word)
        retrieveData(current_user.id, url)
        latest_videos = getLatestVideos(current_user.id)
        getAllChart(word_comments, sentimentDict)
    else:
        new_video(current_user.id, getTitle(vid), url, view_count, like_count, dislike_count, 0, "Not Avaliable")
        retrieveData(current_user.id, url)
        latest_videos = getLatestVideos(current_user.id)
        return render_template("/html/dashboard.html", title = title, error = True, thumbnail = thumbnail, user = user, videos = latest_videos)
    return render_template("/html/dashboard.html", title = title, thumbnail = thumbnail, user = user, videos = latest_videos)

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link rel="stylesheet" href = "{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="dropdown">
        <nav>
            <ul>
                <li><a class="active" href="#home">Home</a></li>
                <li><a class = "FAQ" href = "{{ url_for('faq') }}">FAQ</a></li>
                <li><a href="{{ url_for('about') }}">About Us</a></li>
                <li><a href="{{ url_for('contact') }}">Contact</a></li>
                <li><a href="{{ url_for('privacy')}}">Privacy Policy</a></li>
                <li><a href="{{ url_for('terms') }}">Terms of Use</a></li>
                <li><a href = "{{ url_for('login') }}">login/sign up</a></li>
            </ul>
        </nav>
    </div>
    <h1>YouTube Comment Analyzer</h1>
    <img src="static/images/InsightForge.png" alt="Insight Forge logo for YouTube Comment Analyzer">
    <form action="http://localhost:8008", method="post">
        <label id = "paste" for="url">Paste your video URL below:</label><br>
        <div>
            <input type="text" id="url" name="url" placeholder="Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ">
            <button id = "generate" type="submit">Generate Stats</button>
        </div>
        <input type="number" id="pages" name="pages" placeholder="Pages Of Comments you want (100 comments per page)">
        <input type="checkbox" id="flag" name="flag" value = "1">
        <label id = "translate" for="flag">Translate, if text is not English</label><br><br>
    </form>
    <p1>
        To generate a statistics report, paste the URL for the website in the textbox above, then enter the number of pages you want (100 comments per page)
        , then if your comments are not in English, you can select the box with the "Translate, if text is not English" and finally press
        the "Generate Stats" button.
    </p1> <br><br>
    <p2>
        As of now, this application can only function with YouTube but changes are being made to make it compatible with other websites
    </p2>
</body>
</html>

templates/html/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}InsightForge{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    <script>
      
      document.addEventListener("DOMContentLoaded", function() {
        if (localStorage.getItem("darkMode") === "enabled") {
          document.body.classList.add("dark-mode");
        }
      });

      function toggleDarkMode() {
        let element = document.body;
        element.classList.toggle("dark-mode");

        if (element.classList.contains("dark-mode")) {
          localStorage.setItem("darkMode", "enabled");
        } else {
          localStorage.setItem("darkMode", "disabled");
        }
      }
    </script>
  </head>
  <body>
    <div class="container">
      <header class="header">
        <div class="logo-container">
          <img src="/static/images/InsightForge.png" alt="InsightForge logo" class="logo-image"/>
          <h1 class="logo-text"><a class="nav-item" href="{{ url_for("html.home") }}">InsightForge</h1>
        </div>
        <nav class="nav-menu">
          <ul class="nav-bar">
            <li><a class="nav-item" href="{{ url_for("html.tutorial") }}">Tutorial</a></li>
            <li id="right-item"><a class="login-button" href="http://localhost:8008/logout">Logout</a></li> 
            <button onclick="toggleDarkMode()" class="dark-mode-button">
              <img src="/static/images/moon.png" alt="Dark Mode" class="moon-logo">
            </button> 
          </ul>
        </nav>
      </header>
      {% block content %} {% endblock %}
      </div>
  </body>
</html>

templates/html/dashboard.html
{% extends '/html/base.html' %} {% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">
</head>
<main>
    <h1 class="dashboard-header">{{ title }}</h1>
      <img src="{{ thumbnail }}" alt="Video Thumbnail" class="img-thumbnail">
    <div class="dashboard-flex">
      <div class="word-cloud-column">
        <section class="word-cloud-wrapper">
          <h2 class="word-cloud-title">WordCloud</h2>
          <a href="{{ url_for('static', filename='images/word_cloud.png') }}" class="lightbox">
            <img loading="lazy" src="{% if not error %}{{ url_for('static', filename='images/word_cloud.png') }}{% else %}{{ url_for('static', filename='images/error.png') }}{% endif %}" class="img-2" alt="WordCloud Visualization"/>
          </a>
        </section>
      </div>
      <div class="top-words-column">
        <section class="top-words-wrapper">
          <h2 class="top-words-title">Top 5 Used Words</h2>
          <a href="{% if not error %}{{ url_for('static', filename='images/common_chart.png') }}{% else %}{{ url_for('static', filename='images/error.png') }}{% endif %}" class="lightbox">
            <img loading="lazy" src="{% if not error %}{{ url_for('static', filename='images/common_chart.png') }}{% else %}{{ url_for('static', filename='images/error.png') }}{% endif %}" class="img-3" alt="Top 5 Used Words Visualization"/>
          </a>
        </section>
      </div>
    </div>
    <div class="chart-flex">
      <div class="chart-columns">
        <div class="sentiment-column">
          <section class="sentiment-wrapper">
            <h2 class="sentiment-title">Pie Chart of Sentiments</h2>
            <a href="{{ url_for('static', filename='images/pie_chart.png') }}" class="lightbox">
              <img loading="lazy" src="{% if not error %}{{ url_for('static', filename='images/pie_chart.png') }}{% else %}{{ url_for('static', filename='images/error.png') }}{% endif %}" class="img-4" alt="Pie Chart of Sentiments Visualization"/>
            </a>
          </section>
        </div>
        <div class="statistic-column">
          <section class="statistic-wrapper">
            <h2 class="statistic-title">Statistic Chart</h2>
            <a href="{{ url_for('static', filename='images/stats.png') }}" class="lightbox">
              <img loading="lazy" src="{{ url_for('static', filename='images/stats.png') }}" class="img-5" alt="Statistic Chart Visualization"/>
            </a>
          </section>
        </div>
      </div>
    </div>
    <h3 class="history">User History</h3>
    <ul class="video-history">
      {% for video in videos %}
        <li class="video-entry">
          <div class="video-info">
            <strong>Title:</strong> {{ video.title }}<br>
            <strong>URL:</strong> <a href="{{ video.url }}">{{ video.url }}</a><br>
            <div>
                <strong>Views:</strong> {{ video.views }}<br>
                <strong>Likes:</strong> {{ video.likes }}<br>
                <strong>Dislikes:</strong> {{ video.dislikes }}<br>
                <strong>Score:</strong> {{ video.score }}<br>
                <strong>Most Occurred Word:</strong> {{ video.word }}<br>
                <strong>Date:</strong> {{ video.date }}<br>
            </div>
          </div>
          <hr class="separator">
        </li>
      {% endfor %}
    </ul>
  </main>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
        const lightboxLinks = document.querySelectorAll('.lightbox');
        const lightboxOverlay = document.createElement('div');
        lightboxOverlay.classList.add('lightbox-overlay');
    
        const lightboxImage = document.createElement('img');
        lightboxOverlay.appendChild(lightboxImage);
    
        document.body.appendChild(lightboxOverlay);
    
        lightboxLinks.forEach(link => {
            link.addEventListener('click', function(event) {
                event.preventDefault();
                lightboxImage.src = link.href;
                lightboxOverlay.classList.add('visible');
            });
        });
    
        lightboxOverlay.addEventListener('click', function() {
            lightboxOverlay.classList.remove('visible');
        });
    });
    </script>
  {% endblock %}

templates/html/home.html
{% extends '/html/base.html' %} {% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
    <div class="home-container">
        <div class="content">
            <img src="/static/images/sample.png" alt="Hero image" class="hero-image"/>
            <form action="http://localhost:8008/views/dashboard", method="post">
                <div class="input-container">
                    <div class="input-group">
                        <label for="video-url" class="input-url">Video URL</label>
                        <input type="text" id="video-url" name="url" class="input-field-url" placeholder="https://www.youtube.com/watch?v=jNQXAC9IVRw" aria-label="Enter video URL" required/>
                    </div>
                    <div class="input-group">
                        <label for="page-number" class="input-page">Number of Pages</label>
                        <input type="number" id="page-number" class="input-field-page" name="pages" placeholder="Number of Pages (Each page contains 100 comments)" aria-label="Enter number of pages" required/>
                    </div>
                </div>
                <div class="button">
                    <button class="generate-button" type="submit">Generate</button>
                </div>
            </form>
        </div>
    </div>
</body>
{% endblock %}

templates/html/tutorial.html
{% extends '/html/base.html' %} {% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='tutorial.css') }}">
</head>
    <h2 class="title">Tutorial</h2>
    <section class="tutorial-container">
      <div class="steps-wrapper">
        <article class="step">
          <div class="step-content">
            <img loading="lazy" src="{{ url_for('static', filename='images/copy-url.png') }}" alt="Step 1 Image" class="step-image"/>
            <div class="step-text">Step 1: Copy YouTube URL</div>
          </div>
        </article>
        <article class="step">
          <div class="step-content">
            <img loading="lazy" src="{{ url_for('static', filename='images/paste-url.png') }}" alt="Step 2 Image" class="step-image"/>
            <div class="step-text">Step 2: Paste YouTube URL in the box</div>
          </div>
        </article>
        <article class="step">
          <div class="step-content">
            <img loading="lazy" src="{{ url_for('static', filename='images/select-pages.png') }}" alt="Step 3 Image" class="step-image"/>
            <div class="step-text">Step 3: Select number of comment pages from dropdown</div>
          </div>
        </article>
        <article class="step">
          <div class="step-content">
            <img loading="lazy" src="{{ url_for('static', filename='images/generate-pages.png') }}" alt="Step 4 Image" class="step-image"/>
            <div class="step-text">Step 4: Click ‘Generate’ button to generate results</div>
          </div>
        </article>
      </div>
    </section>
  </div>
</div>
{% endblock %}